/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './src/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        gray: {
          50: '#F7FAFE',
          100: '#EFF4FA',
          200: '#DCE7F6',
          300: '#C5D4E7',
          400: '#95ABCC',
          500: '#627BA6',
          600: '#224077',
          700: '#092253',
          800: '#02173F',
        },
        green: {
          200: '#C6F6D5',
          500: '#48BB78',
          700: '#276749',
        },
        red: {
          100: '#FFF5F5',
          200: '#FED7D7',
          500: '#F56565',
          600: '#C53030',
          700: '#9B2C2C',
        },
        blue: {
          100: '#BEE3F8',
          400: '#4299E1',
          700: '#2C5282',
        },
        orange: {
          200: '#FEEBC8',
          500: '#ED8936',
          700: '#7B341E',
        },
        purple: {
          200: '#E9D8FD',
          500: '#9F7AEA',
          700: '#553C9A',
        },
        brand: {
          100: '#EDF5FD',
          200: '#CCE4FA',
          300: '#0077E41A',
          500: '#3D7014',
          700: '#3c7014',
        },
      },
      fontSize: {
        'xxs': '11px',
        'xs': '13px',
        'sm': '14px',
        'base': '16px',
        'md': '16px',
        'lg': '18px',
        'xl': '24px',
        'xxl': '32px',
        '3xs': '10px',
        '4xs': '9px',
      },
      spacing: {
        'px': '1px',
        '0': '0px',
        '0.5': '2px',
        '0.75': '3px',
        '1': '4px',
        '1.25': '5px',
        '1.5': '6px',
        '2': '8px',
        '2.5': '10px',
        '3': '12px',
        '3.5': '14px',
        '4': '16px',
        '4.5': '18px',
        '5': '20px',
        '6': '24px',
        '6.5': '26px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '11': '44px',
        '12': '48px',
        '13': '52px',
        '14': '56px',
        '15': '60px',
        '16': '64px',
        '17': '68px',
        '18': '72px',
        '19': '76px',
        '20': '80px',
        '21': '84px',
        '22': '88px',
        '-4': '-16px',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        'radio': '14px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      boxShadow: {
        'errorToast': '0px 2px 6px rgba(15, 48, 98, 0.25)',
        'centeredContainer': '0px 12px 24px rgba(0, 77, 148, 0.1)',
        'roleContainer': 'inset 0px -3px 0px rgba(197, 212, 231, 0.34)',
        'secondary': 'inset 0px -2px 0px rgba(104, 125, 160, 0.25)',
        'dialog': '0px 8px 16px rgba(0, 0, 0, 0.15)',
        'popover': '0px 4px 16px rgba(0, 0, 0, 0.15)',
      },
      lineHeight: {
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '2.5': '10px',
        '3': '12px',
        '3.5': '14px',
        '4': '16px',
        '4.5': '18px',
        '5': '20px',
        '5.5': '22px',
        '6': '24px',
        '6.5': '26px',
        '6.75': '27px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '11': '44px',
        '12': '48px',
      },
      fontFamily: {
        asap: ['var(--font-asap)', 'sans-serif'],
      },
    },
    screens: {
      'sm': '480px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1600px',
    },
  },
  plugins: [require("tailwindcss-animate")],
}
